name: Security Scan with Trivy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  security-scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DISABLE_VEX_NOTICE: true
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          vuln-type: 'os,library'
          ignore-unfixed: true
          output: 'trivy_report.txt'

      - name: Check if report exists and has content
        id: check_report
        run: |
          if [ -f trivy_report.txt ] && [ -s trivy_report.txt ]; then
            echo "Report exists and has content"
            cat trivy_report.txt
          else
            echo "No vulnerabilities found" > trivy_report.txt
          fi

      - name: Read Full Trivy Report
        id: read_report
        run: |
          {
            echo "REPORT<<EOF"
            cat trivy_report.txt
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Comment Full Trivy Report on PR
        uses: peter-evans/create-or-update-comment@v4
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🔍 Trivy Security Scan Results
            ```
            ${{ env.REPORT }}
            ```
          token: ${{ secrets.GITHUB_TOKEN }}